spring:
  kafka:
    bootstrap-servers: localhost:10000, localhost:10001, localhost:10002
    consumer:
      group-id: point-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:mysql://localhost:3306/pl_point_v1
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 80
      minimum-idle: 30
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka